"use strict";
var fs = require("fs");
var vm = require("vm");
var path = require("path");
var H = require("./harness");
var ROOT = path.resolve(__dirname, "..", "..");
var G = H.boot();
vm.runInThisContext(fs.readFileSync(path.join(ROOT, "web", "js", "life.js"), "utf8"), { filename: "life.js" });
var pass = 0, fail = 0;
function ok(c, s) { if (c) { pass++; console.log("  ✓ " + s); } else { fail++; console.log("  ✗ " + s); } }
console.log("\n— V3-002: реальные последствия поведения");
G.Save.set("igra.life.v1", JSON.stringify({ skins: 1, legacy: true, behavior: { born: 20, returns: 7, pulses: 4, still: 90, motion: 10 }, traits: ["curiosity"], lastTrait: "curiosity" }));
G.Life.resetCache();
var game = H.makeWorld(G, 4402);
var before = game.world.nodes.length;
G.Life.applyConsequences(game);
ok(game.__lifeConsequences.return3 && game.__lifeConsequences.return7, "возвращения получают два устойчивых следствия");
ok(game.world.nodes.some(function(n){return n.memory && n.verse === "ты вернулся";}), "возвращение оставляет узнаваемый след в мире");
ok(game.__lifeConsequences.pulse4 === true && game.world.wounds.length >= 1, "частый пульс оставляет напряжение/рану");
ok(game.__lifeConsequences.still90 === true, "долгое созерцание фиксируется как последствие");
ok(game.world.nodes.length >= before, "последствия не ломают генерацию берега");
var snapshot = JSON.stringify(game.__lifeConsequences);
G.Life.applyConsequences(game);
ok(snapshot === JSON.stringify(game.__lifeConsequences), "последствия идемпотентны");
G.Life.resetCache();
var loaded = G.Life.profile();
ok(loaded.behavior.returns === 7 && loaded.behavior.pulses === 4, "поведенческий отпечаток переживает перезагрузку");
console.log("\nИтого: " + pass + " passed, " + fail + " failed");
if (fail) process.exit(1);
