"use strict";
var assert = require("assert"), fs = require("fs"), vm = require("vm");
var ctx = { console: console, Math: Math };
vm.createContext(ctx);
["v12-lineage.js"].forEach(function (f) { vm.runInContext(fs.readFileSync("web/js/" + f, "utf8"), ctx, { filename: f }); });
var G = ctx.IGRA;
assert(G && G.V12Lineage, "V12 lineage layer loads");
var world = {};
var first = G.V12Lineage.ensure(world);
assert.strictEqual(first.generation, 0, "fresh lineage starts at generation zero");
assert(Array.isArray(first.ancestors) && first.ancestors.length === 0, "fresh ancestry is empty");
var parent = { id: "ancestor-1", kind: "empathy", personality: { empathy: 0.8, curiosity: 0.4 } };
var inherited = G.V12Lineage.inherit(world, parent);
assert.strictEqual(inherited.generation, 1, "first inheritance advances generation");
assert.strictEqual(inherited.ancestors[0].id, "ancestor-1", "parent identity is retained");
assert.strictEqual(inherited.ancestors[0].kind, "empathy", "parent kind is retained");
assert.strictEqual(inherited.traits.empathy, 0.68, "traits inherit with bounded attenuation");
assert.strictEqual(inherited.traits.curiosity, 0.34, "multiple traits inherit deterministically");
for (var i = 2; i <= 12; i++) G.V12Lineage.inherit(world, { id: "ancestor-" + i, kind: "kind-" + i, traits: { harmony: 1 } });
assert.strictEqual(world.lineageV12.generation, 12, "generation remains deterministic across repeated inheritance");
assert(world.lineageV12.ancestors.length <= 8, "ancestry is bounded");
assert(world.lineageV12.traits.harmony <= 0.85, "trait inheritance remains bounded");
var world2 = {};
for (var j = 1; j <= 12; j++) G.V12Lineage.inherit(world2, { id: "ancestor-" + j, kind: "kind-" + j, traits: { harmony: 1 } });
assert.strictEqual(JSON.stringify(world.lineageV12), JSON.stringify(world2.lineageV12), "same inheritance sequence is deterministic");
console.log("V12 lineage probe: PASS");
